sources:
  caldera:
    kind: dockerimage
    spec:
      image: openaev/caldera-server
      architecture: linux/amd64
      versionFilter:
        kind: semver
        pattern: '*'
  minio:
    kind: helmchart
    spec:
      url: https://charts.min.io/
      name: minio
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: minio
  opensearch:
    kind: helmchart
    spec:
      url: https://opensearch-project.github.io/helm-charts/
      name: opensearch
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: opensearch
  postgresql:
    kind: helmchart
    spec:
      url: https://charts.bitnami.com/bitnami
      name: postgresql
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: postgresql
  rabbitmq:
    kind: helmchart
    spec:
      url: https://charts.bitnami.com/bitnami
      name: rabbitmq
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: rabbitmq
conditions: {}
targets:
  caldera:
    name: bump chart caldera tag
    kind: yaml
    spec:
      file: charts/openaev/values.yaml
      key: $.caldera.image.tag
    sourceid: caldera
  minio:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/openaev/Chart.yaml
      key: $.dependencies[0].version
    sourceid: minio
  opensearch:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/openaev/Chart.yaml
      key: $.dependencies[1].version
    sourceid: opensearch
