sources:
  openbas:
    kind: dockerimage
    spec:
      image: openbas/platform
      architecture: linux/amd64
      versionFilter:
        kind: semver
conditions: {}
targets:
  openbas:
    name: bump chart appversion
    kind: yaml
    spec:
      file: charts/openbas/Chart.yaml
      key: $.appVersion
    sourceid: openbas
