sources:
  openaev:
    kind: dockerimage
    spec:
      image: openaev/platform
      architecture: linux/amd64
      versionFilter:
        kind: semver
conditions: {}
targets:
  openaev:
    name: bump chart appversion
    kind: yaml
    spec:
      file: charts/openaev/Chart.yaml
      key: $.appVersion
    sourceid: openaev
