{{- range .Values.collectors }}
{{- $collectorName := .name }}

{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $collectorName }}-collector-{{ include "openbas.fullname" $ }}
  labels:
    openbas.collector: {{ $collectorName }}
    {{- include "openbas.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling }}
  replicas: {{ .replicas }}
  {{- end }}
  selector:
    matchLabels:
      openbas.collector: {{ $collectorName }}
      {{- include "openbas.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        openbas.collector: {{ $collectorName }}
        {{- include "openbas.selectorLabels" $ | nindent 8 }}
    spec:
      {{- if .imagePullSecrets }}
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else if $.Values.global.imagePullSecrets }}
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $collectorName }}-collector
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{- if .image.repository }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          {{- else if $.Values.global.imageRegistry }}
          image: "{{ printf "%s/openbas/collector-%s" $.Values.global.imageRegistry .name }}:{{ .image.tag | default $.Chart.AppVersion }}"
          {{- else }}
          image: "{{ printf "openbas/collector-%s" .name }}:{{ .image.tag | default $.Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          env:
          # Variables from secrets have precedence
          {{- $envList := dict -}}

          {{- if .envFromSecrets }}
          {{- range $key, $value := .envFromSecrets }}
          - name: {{ $key | upper }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name }}
                key: {{ $value.key | default $key }}
          {{- $_ := set $envList $key true }}
          {{- end }}
          {{- end }}

          # Special handling for OPENBAS_URL which is constructed from other values
          {{- if not (hasKey .env "OPENBAS_URL") }}
          - name: OPENBAS_URL
            value: "http://{{ include "openbas.fullname" $ }}-server:{{ $.Values.service.port }}"
          {{- end }}

          # Special handling for OPENBAS_TOKEN which is constructed from other values
          {{- if and (not (hasKey .env "OPENBAS_TOKEN")) ($.Values.env.OPENBAS_ADMIN_TOKEN) }}
          - name: OPENBAS_TOKEN
            value: "{{ $.Values.env.OPENBAS_ADMIN_TOKEN }}"
          {{- end }}

          # Add Variables in plain text if they were not already added from secrets
          {{- if .env }}
          {{- range $key, $value := .env }}
          {{- if not (hasKey $envList $key) }}
          - name: {{ $key | upper }}
            value: {{ $value | quote }}
          {{- $_ := set $envList $key true }}
          {{- end }}
          {{- end }}
          {{- end }}

          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
{{- end }}
