{{- range .Values.injectors }}
{{- $injectorName := .name }}

{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $injectorName }}-injector-{{ include "openbas.fullname" $ }}
  {{- with .deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    openbas.injector: {{ $injectorName }}
    {{- include "openbas.labels" $ | nindent 4 }}
spec:
  {{- if not .autoscaling }}
  replicas: {{ .replicas }}
  {{- end }}
  selector:
    matchLabels:
      openbas.injector: {{ $injectorName }}
      {{- include "openbas.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        openbas.injector: {{ $injectorName }}
        {{- include "openbas.selectorLabels" $ | nindent 8 }}
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      {{- else if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .serviceAccount }}
      serviceAccountName: {{ if and .serviceAccount (hasKey .serviceAccount "name") }}{{ .serviceAccount.name }}{{ else }}{{ $injectorName }}-injector-{{ include "openbas.fullname" $ }}{{ end }}
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      {{ if and .readyChecker (hasKey .readyChecker "enabled") }}
      {{- if .readyChecker.enabled }}
      initContainers:
      - name: ready-checker-server
        {{- if $.Values.global.imageRegistry }}
        image: "{{ $.Values.global.imageRegistry }}/busybox"
        {{- else }}
        image: busybox
        {{- end }}
        command:
          - 'sh'
          - '-c'
          - >
            RETRY=0;
            until [ $RETRY -eq {{ .readyChecker.retries }} ];
            do
              nc -zv {{ $.Values.fullnameOverride | default (include "openbas.fullname" $) }}-server {{ $.Values.service.port }} && break;
              echo "[$RETRY/{{ .readyChecker.retries }}] waiting service {{ $.Values.fullnameOverride | default (include "openbas.fullname" $) }}-server:{{ $.Values.service.port }} is ready";
              sleep {{ .readyChecker.timeout }};
              RETRY=$(($RETRY + 1));
            done
      {{- end }}
      {{- end }}
      containers:
        - name: {{ $injectorName }}-injector
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{- if and .image (hasKey .image "repository") }}{{ .image.repository }}{{- else if $.Values.global.imageRegistry }}{{ printf "%s/openbas/%s" $.Values.global.imageRegistry .name }}{{- else }}{{ printf "openbas/%s" .name }}{{- end }}:{{ if and .image (hasKey .image "tag") }}{{ .image.tag | default $.Chart.AppVersion }}{{ else }}{{ $.Chart.AppVersion }}{{ end }}"
          imagePullPolicy: {{ if and .image (hasKey .image "pullPolicy") }}{{ .image.pullPolicy }}{{ else }}IfNotPresent{{ end }}
          env:
          # Variables from secrets have precedence
          {{- $envList := dict -}}
          {{- if .envFromSecrets }}
          {{- range $key, $value := .envFromSecrets }}
          - name: {{ $key | upper }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name }}
                key: {{ $value.key | default $key }}
          {{- $_ := set $envList $key true }}
          {{- end }}
          {{- end }}
          # Add variables in plain text if they were not already added from secrets
          {{- if .env }}
          {{- range $key, $value := .env }}
          {{- if not (hasKey $envList $key) }}
          - name: {{ $key | upper }}
            value: {{ $value | quote }}
          {{- $_ := set $envList $key true }}
          {{- end }}
          {{- end }}
          {{- end }}
          # Special handling for OPENBAS_URL which is constructed from other values
          {{- if not (hasKey $envList "OPENBAS_URL") }}
          {{- if eq $.Values.env.APP__BASE_PATH "/" }}
          - name: OPENBAS_URL
            value: "http://{{ include "openbas.fullname" $ }}-server:{{ $.Values.service.port }}"
          {{- else }}
          - name: OPENBAS_URL
            value: "http://{{ include "openbas.fullname" $ }}-server:{{ $.Values.service.port }}{{ $.Values.env.APP__BASE_PATH }}"
          {{- end }}
          {{- end }}
          # Special handling for OPENBAS_TOKEN which is constructed from other values
          {{- if and (not (hasKey $envList "OPENBAS_TOKEN")) (or ($.Values.secrets.OPENBAS_ADMIN_TOKEN) ($.Values.env.OPENBAS_ADMIN_TOKEN)) }}
          {{- if $.Values.secrets.OPENBAS_ADMIN_TOKEN }}
          - name: OPENBAS_TOKEN
            value: {{ $.Values.secrets.OPENBAS_ADMIN_TOKEN }}
          {{- else if $.Values.env.OPENBAS_ADMIN_TOKEN }}
          - name: OPENBAS_TOKEN
            value: {{ $.Values.env.OPENBAS_ADMIN_TOKEN }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
{{- end }}
