{{- range .Values.injectors }}
{{- $injectorName := .name }}

{{ if and .serviceAccount (hasKey .serviceAccount "create") }}
{{- if .serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if and .serviceAccount (hasKey .serviceAccount "name") }}{{ .serviceAccount.name }}{{ else }}{{ $injectorName }}-injector-{{ include "openbas.fullname" $ }}{{ end }}
  labels:
    openbas.injector: {{ $injectorName }}
    {{- include "openbas.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .serviceAccount.automountServiceAccountToken | default "false" }}
{{- end }}
{{- end }}

{{- end }}
