apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbas.fullname" . }}-caldera
  labels:
    {{- include "openbas.calderaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.caldera.service.type }}
  ports:
    - port: {{ .Values.caldera.service.port }}
      targetPort: {{ .Values.caldera.service.targetPort | default .Values.caldera.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "openbas.selectorCalderaLabels" . | nindent 4 }}
