apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbas.fullname" . }}-caldera
  labels:
    openbas.component: caldera
    {{- include "openbas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.caldera.service.type }}
  ports:
    - port: {{ .Values.caldera.service.port }}
      targetPort: {{ .Values.caldera.service.targetPort | default .Values.caldera.service.port }}
      protocol: TCP
      name: http
  selector:
    openbas.component: caldera
    {{- include "openbas.selectorLabels" . | nindent 4 }}
