apiVersion: v2
name: openbas
description: A Helm chart to deploy Open Breach and Attack Simulation platform
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/devops-ia/helm-openbas
  - https://github.com/OpenBAS-Platform/openbas
version: 1.0.0
appVersion: 1.14.1
home: https://www.filigran.io/en/solutions/products/openbas/
keywords:
  - openbas
  - cybersecurity
  - purple-team
  - attack-simulation
  - breach-simulator
  - threat
  - analysis
dependencies:
  - name: minio
    version: 15.0.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
  - name: postgresql
    version: 16.6.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: rabbitmq
    version: 15.4.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled
