# http-query
# ref: https://github.com/OpenBAS-Platform/injectors/blob/main/http-query
- name: http-query
  enabled: true
  replicas: 1
  image: {}
  env:
    OPENBAS_URL: http://localhost
    OPENBAS_TOKEN: ChangeMe
    INJECTOR_ID: ChangeMe
    INJECTOR_NAME: "HTTP query"
    INJECTOR_LOG_LEVEL: error
