# atomic-red-team
# ref: https://github.com/OpenBAS-Platform/collectors/tree/main/atomic-red-team
- name: atomic-red-team
  enabled: true
  replicas: 1
  image: {}
  env:
    OPENBAS_URL: http://localhost
    OPENBAS_TOKEN: ChangeMe
    COLLECTOR_ID: ChangeMe
    COLLECTOR_NAME: "Atomic Red Team"
    COLLECTOR_LOG_LEVEL: error
