replicaCount: 1
fullnameOverride: openbas-ci

secrets:
  OPENCTI_TOKEN: my-ci-cd

env:
  INJECTOR_CALDERA_API_KEY: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
  INJECTOR_CALDERA_PUBLIC_URL: http://openbas-ci-caldera:8888
  INJECTOR_CALDERA_URL: http://openbas-ci-caldera:8888
  LOGGING_LEVEL_IO_OPENBAS: info
  LOGGING_LEVEL_ROOT: info
  MINIO_ACCESS-KEY: ChangeMe
  MINIO_ACCESS-SECRET: ChangeMe
  MINIO_ENDPOINT: openbas-ci-minio
  OPENBAS_ADMIN_EMAIL: admin@openbas.io
  OPENBAS_ADMIN_PASSWORD: test
  OPENBAS_ADMIN_TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
  OPENBAS_BASE-URL: http://openbas-ci:8080
  OPENBAS_RABBITMQ_HOSTNAME: openbas-ci-rabbitmq
  OPENBAS_RABBITMQ_MANAGEMENT-PORT: 15672
  OPENBAS_RABBITMQ_PASS: ChangeMe
  OPENBAS_RABBITMQ_PORT: 5672
  OPENBAS_RABBITMQ_USER: user
  SPRING_DATASOURCE_PASSWORD: ChangeMe
  SPRING_DATASOURCE_URL: jdbc:postgresql://openbas-ci-postgresql:5432/openbas
  SPRING_DATASOURCE_USERNAME: user

testConnection: false

autoscaling:
  enabled: true

caldera:
  enabled: true
  env:
    CALDERA_URL: http://openbas-ci-caldera:8888
  config:
    users:
      red:
        red: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
      blue:
        blue: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    api_key_red: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    api_key_blue: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    api_key: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    crypt_salt: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    encryption_key: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    app.contact.tcp: 0.0.0.0:7010
    app.contact.udp: 0.0.0.0:7011
    app.contact.websocket: 0.0.0.0:7012
    app.contact.dns.domain: localhost
    app.contact.dns.socket: 0.0.0.0:53
    app.contact.http: http://openbas-ci-caldera:8888
    app.contact.tunnel.ssh.user_password: 0ce2182d-3e1a-4117-a1d4-8100a7b01d82
    app.contact.tunnel.ssh.socket: 0.0.0.0:8022
    app.contact.tunnel.ssh.user_name: sandcat
    objects.planners.default: atomic
    requirements:
      go:
        command: go version
        type: installed_program
        version: 1.11
      python:
        attr: version
        module: sys
        type: python_module
        version: 3.8.0
    host: 0.0.0.0
    port: 8888
    ability_refresh: 60
    plugins:
      - access
      - atomic
      - compass
      - debrief
      - fieldmanual
      - gameboard
      - manx
      - response
      - sandcat
      - stockpile
      - training

collectors:
- name: atomic-red-team
  enabled: true
  replicas: 1
  image: {}
  serviceAccount:
    name: openbas-collector-ci
  deploymentAnnotations:
    ci: "true"
  podAnnotations:
    ci: "true"
  env:
    OPENBAS_URL: http://localhost
    OPENBAS_TOKEN: ChangeMe
    COLLECTOR_ID: ChangeMe
    COLLECTOR_NAME: "Atomic Red Team"
    COLLECTOR_LOG_LEVEL: error

injectors:
- name: http-query
  enabled: true
  replicas: 1
  serviceAccount:
    name: openbas-injector-ci
  deploymentAnnotations:
    ci: "true"
  podAnnotations:
    ci: "true"
  env:
    OPENBAS_URL: http://localhost
    OPENBAS_TOKEN: ChangeMe
    INJECTOR_ID: ChangeMe
    INJECTOR_NAME: "HTTP query"
    INJECTOR_LOG_LEVEL: error

minio:
  fullnameOverride: openbas-ci-minio

postgresql:
  fullnameOverride: openbas-ci-postgresql
  database: "openbas"

rabbitmq:
  fullnameOverride: openbas-ci-rabbitmq
  auth:
    erlangCookie: b25c953e-2193-4b8e-9f3b-9a3a5ba76d75
