name: Lint and test PR OpenBAS

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # default install latest (stable)
      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "${changed}" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run ct lint
        if: steps.list-changed.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        run: ct lint --config .github/ct.yaml --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: helm/kind-action@v1

      - name: Run ct install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config .github/ct.yaml --helm-extra-args '--timeout 900s --debug' --target-branch ${{ github.event.repository.default_branch }}

      - name: (workflow_dispatch) Run ct install
        if: github.event_name == 'workflow_dispatch'
        run: ct install --config .github/ct.yaml --helm-extra-args '--timeout 900s --debug' --all --target-branch ${{ github.event.repository.default_branch }}
